import { Download, FileText } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { downloadReport } from "@/services/reportService";
import type { GeneratedReport } from "@/types/reports";

export function ReportPreview({
  report,
  open,
  onOpenChange,
}: {
  report: GeneratedReport | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  if (!report) return null;
  const { metadata } = report;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="size-4 text-primary" />
            {metadata.title}
          </DialogTitle>
          <DialogDescription>
            Report generated successfully. Review the details before downloading.
          </DialogDescription>
        </DialogHeader>

        <dl className="grid gap-4 rounded-md border border-border bg-muted/40 p-4 sm:grid-cols-3">
          {[
            ["Report ID", metadata.report_id],
            ["Generated", metadata.generated_at],
            ["Pages", String(report.page_count)],
            ["Generated by", `${metadata.generated_by} · ${metadata.generated_by_role}`],
            ["File name", metadata.filename],
            ...metadata.subjects.map((s) => [s.label, s.value] as [string, string]),
          ].map(([label, value]) => (
            <div key={label} className="min-w-0">
              <dt className="text-[11px] uppercase tracking-wider text-muted-foreground">{label}</dt>
              <dd className="truncate text-xs font-medium text-foreground" title={value}>
                {value}
              </dd>
            </div>
          ))}
        </dl>

        <div className="h-[420px] overflow-hidden rounded-md border border-border bg-muted">
          <iframe title="Report preview" src={report.url} className="size-full" />
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Close
          </Button>
          <Button onClick={() => downloadReport(report)}>
            <Download className="size-4" /> Download PDF
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
