/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell.analytics'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellDataQualityRouteImport } from './routes/_shell.data-quality'
import { Route as ShellFraudAnalysisRouteImport } from './routes/_shell.fraud-analysis'
import { Route as ShellImportRouteImport } from './routes/_shell.import'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellClaimsIndexRouteImport } from './routes/_shell.claims.index'
import { Route as ShellClaimsClaimIdRouteImport } from './routes/_shell.claims.$claimId'
import { Route as ShellInvestigationsIndexRouteImport } from './routes/_shell.investigations.index'
import { Route as ShellInvestigationsCaseIdRouteImport } from './routes/_shell.investigations.$caseId'
import { Route as ShellProvidersIndexRouteImport } from './routes/_shell.providers.index'
import { Route as ShellProvidersProviderIdRouteImport } from './routes/_shell.providers.$providerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDataQualityRoute = ShellDataQualityRouteImport.update({
  id: '/data-quality',
  path: '/data-quality',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFraudAnalysisRoute = ShellFraudAnalysisRouteImport.update({
  id: '/fraud-analysis',
  path: '/fraud-analysis',
  getParentRoute: () => ShellRoute,
} as any)
const ShellImportRoute = ShellImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClaimsIndexRoute = ShellClaimsIndexRouteImport.update({
  id: '/claims/',
  path: '/claims/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClaimsClaimIdRoute = ShellClaimsClaimIdRouteImport.update({
  id: '/claims/$claimId',
  path: '/claims/$claimId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInvestigationsIndexRoute =
  ShellInvestigationsIndexRouteImport.update({
    id: '/investigations/',
    path: '/investigations/',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellInvestigationsCaseIdRoute =
  ShellInvestigationsCaseIdRouteImport.update({
    id: '/investigations/$caseId',
    path: '/investigations/$caseId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellProvidersIndexRoute = ShellProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProvidersProviderIdRoute =
  ShellProvidersProviderIdRouteImport.update({
    id: '/providers/$providerId',
    path: '/providers/$providerId',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/data-quality': typeof ShellDataQualityRoute
  '/fraud-analysis': typeof ShellFraudAnalysisRoute
  '/import': typeof ShellImportRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/claims/$claimId': typeof ShellClaimsClaimIdRoute
  '/investigations/$caseId': typeof ShellInvestigationsCaseIdRoute
  '/providers/$providerId': typeof ShellProvidersProviderIdRoute
  '/claims/': typeof ShellClaimsIndexRoute
  '/investigations/': typeof ShellInvestigationsIndexRoute
  '/providers/': typeof ShellProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/data-quality': typeof ShellDataQualityRoute
  '/fraud-analysis': typeof ShellFraudAnalysisRoute
  '/import': typeof ShellImportRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/claims/$claimId': typeof ShellClaimsClaimIdRoute
  '/investigations/$caseId': typeof ShellInvestigationsCaseIdRoute
  '/providers/$providerId': typeof ShellProvidersProviderIdRoute
  '/claims': typeof ShellClaimsIndexRoute
  '/investigations': typeof ShellInvestigationsIndexRoute
  '/providers': typeof ShellProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/data-quality': typeof ShellDataQualityRoute
  '/_shell/fraud-analysis': typeof ShellFraudAnalysisRoute
  '/_shell/import': typeof ShellImportRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/claims/$claimId': typeof ShellClaimsClaimIdRoute
  '/_shell/investigations/$caseId': typeof ShellInvestigationsCaseIdRoute
  '/_shell/providers/$providerId': typeof ShellProvidersProviderIdRoute
  '/_shell/claims/': typeof ShellClaimsIndexRoute
  '/_shell/investigations/': typeof ShellInvestigationsIndexRoute
  '/_shell/providers/': typeof ShellProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/dashboard'
    | '/data-quality'
    | '/fraud-analysis'
    | '/import'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/claims/$claimId'
    | '/investigations/$caseId'
    | '/providers/$providerId'
    | '/claims/'
    | '/investigations/'
    | '/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/dashboard'
    | '/data-quality'
    | '/fraud-analysis'
    | '/import'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/claims/$claimId'
    | '/investigations/$caseId'
    | '/providers/$providerId'
    | '/claims'
    | '/investigations'
    | '/providers'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/analytics'
    | '/_shell/dashboard'
    | '/_shell/data-quality'
    | '/_shell/fraud-analysis'
    | '/_shell/import'
    | '/_shell/profile'
    | '/_shell/reports'
    | '/_shell/settings'
    | '/_shell/claims/$claimId'
    | '/_shell/investigations/$caseId'
    | '/_shell/providers/$providerId'
    | '/_shell/claims/'
    | '/_shell/investigations/'
    | '/_shell/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/data-quality': {
      id: '/_shell/data-quality'
      path: '/data-quality'
      fullPath: '/data-quality'
      preLoaderRoute: typeof ShellDataQualityRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/fraud-analysis': {
      id: '/_shell/fraud-analysis'
      path: '/fraud-analysis'
      fullPath: '/fraud-analysis'
      preLoaderRoute: typeof ShellFraudAnalysisRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/import': {
      id: '/_shell/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ShellImportRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/claims/': {
      id: '/_shell/claims/'
      path: '/claims'
      fullPath: '/claims/'
      preLoaderRoute: typeof ShellClaimsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/claims/$claimId': {
      id: '/_shell/claims/$claimId'
      path: '/claims/$claimId'
      fullPath: '/claims/$claimId'
      preLoaderRoute: typeof ShellClaimsClaimIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/investigations/': {
      id: '/_shell/investigations/'
      path: '/investigations'
      fullPath: '/investigations/'
      preLoaderRoute: typeof ShellInvestigationsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/investigations/$caseId': {
      id: '/_shell/investigations/$caseId'
      path: '/investigations/$caseId'
      fullPath: '/investigations/$caseId'
      preLoaderRoute: typeof ShellInvestigationsCaseIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/providers/': {
      id: '/_shell/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ShellProvidersIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/providers/$providerId': {
      id: '/_shell/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof ShellProvidersProviderIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDataQualityRoute: typeof ShellDataQualityRoute
  ShellFraudAnalysisRoute: typeof ShellFraudAnalysisRoute
  ShellImportRoute: typeof ShellImportRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellClaimsClaimIdRoute: typeof ShellClaimsClaimIdRoute
  ShellInvestigationsCaseIdRoute: typeof ShellInvestigationsCaseIdRoute
  ShellProvidersProviderIdRoute: typeof ShellProvidersProviderIdRoute
  ShellClaimsIndexRoute: typeof ShellClaimsIndexRoute
  ShellInvestigationsIndexRoute: typeof ShellInvestigationsIndexRoute
  ShellProvidersIndexRoute: typeof ShellProvidersIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDataQualityRoute: ShellDataQualityRoute,
  ShellFraudAnalysisRoute: ShellFraudAnalysisRoute,
  ShellImportRoute: ShellImportRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellClaimsClaimIdRoute: ShellClaimsClaimIdRoute,
  ShellInvestigationsCaseIdRoute: ShellInvestigationsCaseIdRoute,
  ShellProvidersProviderIdRoute: ShellProvidersProviderIdRoute,
  ShellClaimsIndexRoute: ShellClaimsIndexRoute,
  ShellInvestigationsIndexRoute: ShellInvestigationsIndexRoute,
  ShellProvidersIndexRoute: ShellProvidersIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
